import streamlit as st

def render(state):
    st.header("A7: Novelty & Emerging Trends")
    
    # 1. Safely extract the data generated by Agent 7
    novelty_data = state.get("A7_novelty_data", {})
    # Note: Using 'novelty_score' to match Agent 7 output keys
    score = novelty_data.get("novelty_score", 0.0) 
    is_anomaly = novelty_data.get("is_anomaly", False)
    patterns = novelty_data.get("anomalous_patterns", [])
    recommendation = novelty_data.get("strategic_recommendation", "No recommendation available.")
    
    # 2. Main Metric Display
    st.metric(
        "Global Novelty Index", 
        f"{score:.4f}", 
        delta="High Alert / Emerging" if is_anomaly else "Stable Trends"
    )
    
    st.divider()
    
    # 3. Dynamic Emerging Trend Analysis
    # This replaces the hardcoded "Late Night" placeholder with actual AI insights
    st.subheader("Emerging Trend Analysis")
    if patterns:
        for pattern in patterns:
            # Renders each pattern identified by the LLM
            st.warning(f"AI Detected Signal: {pattern}")
    else:
        st.info("No anomalous patterns detected in current dataset.")

    # 4. Strategic Recommendation Block
    if recommendation:
        st.success(f"**Strategic Pivot:** {recommendation}")

    # 5. Safe Reasoning Trace
    reasoning = state.get("A7_reasoning", "No trace available.")
    with st.expander("View Anomaly Detection Trace"):
        st.markdown(f'<div class="reasoning-box">{reasoning}</div>', unsafe_allow_html=True)

    st.divider()
    
    # 6. Final Navigation Button
    if st.button("Complete Analysis Flow →", type="primary"):
        st.session_state.current_step = 8
        st.success("Pipeline Analysis Complete. You can now reset filters in the sidebar.")